BakendProject/ViewComponents/FooterViewComponent.cs
using BakendProject.DAL;
using BakendProject.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace BakendProject.ViewComponents
{
    public class FooterViewComponent : ViewComponent
    {
        private readonly AppDbContext _context;
        public FooterViewComponent(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            Bio bio = _context.Bios.FirstOrDefault();
            return View(await Task.FromResult(bio));
        }
    }
}

BakendProject/ViewComponents/HeaderViewComponent.cs
using BakendProject.DAL;
using BakendProject.Models;
using BakendProject.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BakendProject.ViewComponents
{
    public class HeaderViewComponent : ViewComponent
    {
        private readonly AppDbContext _context;
        public HeaderViewComponent(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<Bio> dbBio = _context.Bios.ToList();

            List<Category> dbCategories = _context.Categories.Where(c => c.ParentId == null).ToList();
            List<Category> dbSubCategories = _context.Categories.OrderBy(c => c.ParentId == c.Id).ToList();
            



            HeaderVM headerVM = new HeaderVM();
            headerVM.bios = dbBio;
            headerVM.categories = dbCategories;
            headerVM.subCategories = dbSubCategories;


            return View(await Task.FromResult(headerVM));
        }
    }
}

BakendProject/Views/Shared/_Layout.cshtml
<!doctype html>
<html class="no-js" lang="en">


<!-- Mirrored from demo.hasthemes.com/allup/allup/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 04 Sep 2020 10:46:32 GMT -->
<head>
    <meta charset="utf-8">

    <!--====== Title ======-->
    <title>Allup - Electronics Responsive eCommerce HTML Template.</title>

    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--====== Favicon Icon ======-->
    <link rel="shortcut icon" href="~/images/favicon.png" type="image/png">


    <!-- CSS
	============================================ -->

    <!--===== Vendor CSS (Bootstrap & Icon Font) =====-->
    
    <link rel="stylesheet" href="~/css/plugins/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/plugins/ionicons.min.css">
    <link rel="stylesheet" href="~/css/plugins/fontawesome.min.css">

    <!--===== Plugins CSS (All Plugins Files) =====-->
    
    <link rel="stylesheet" href="~/css/plugins/slick.css">
    <link rel="stylesheet" href="~/css/plugins/animate.css">
    <link rel="stylesheet" href="~/css/plugins/jquery-ui.min.css">
    <link rel="stylesheet" href="~/css/plugins/default.css">

    <!--====== Main Style CSS ======-->
    <link rel="stylesheet" href="~/css/style.css">


    <!--====== Use the minified version files listed below for better performance and remove the files listed above ======-->

    <!-- <link rel="stylesheet" href="assets/css/vendor/plugins.min.css">
    <link rel="stylesheet" href="assets/css/style.min.css"> -->

</head>
<body>
    @await Component.InvokeAsync("Header");
        @RenderBody()
       @await Component.InvokeAsync("Footer");




    <!--====== Vendors js ======-->
    <script src="~/js/vendor/jquery-1.12.4.min.js"></script>
    <script src="~/js/vendor/modernizr-3.7.1.min.js"></script>

    <!--====== Plugins js ======-->
    <script src="~/js/plugins/popper.min.js"></script>
    <script src="~/js/plugins/bootstrap.min.js"></script>
    <script src="~/js/plugins/slick.min.js"></script>
    <script src="~/js/plugins/jquery.countdown.min.js"></script>
    <script src="~/js/plugins/jquery-ui.min.js"></script>


    <!--====== Use the minified version files listed below for better performance and remove the files listed above ======-->

    <!-- <script src="assets/js/plugins.min.js"></script> -->
    

    <!--====== Main Activation js ======-->
    <script src="~/js/main.js"></script>


    

</body>


<!-- Mirrored from demo.hasthemes.com/allup/allup/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 04 Sep 2020 10:47:16 GMT -->
</html>